-- MySQL Script generated by MySQL Workbench
-- jue 09 nov 2017 18:28:54 ART
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pizzaok
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pizzaok` ;

-- -----------------------------------------------------
-- Schema pizzaok
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzaok` DEFAULT CHARACTER SET utf8 ;
USE `pizzaok` ;

-- -----------------------------------------------------
-- Table `pizzaok`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaok`.`Cliente` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzaok`.`EstadoPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaok`.`EstadoPedido` (
  `idEstadoPedido` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstadoPedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzaok`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaok`.`Pedido` (
  `idPedido` INT(11) NOT NULL AUTO_INCREMENT,
  `idCliente` INT(11) NOT NULL,
  `idEstadoPedido` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `idCliente_idx` (`idCliente` ASC),
  INDEX `idEstadoPedido_idx` (`idEstadoPedido` ASC),
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `pizzaok`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idEstadoPedido`
    FOREIGN KEY (`idEstadoPedido`)
    REFERENCES `pizzaok`.`EstadoPedido` (`idEstadoPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzaok`.`TamanoPizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaok`.`TamanoPizza` (
  `idTamanoPizza` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cantPorciones` INT(3) NOT NULL,
  PRIMARY KEY (`idTamanoPizza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzaok`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaok`.`Pizza` (
  `idPizza` INT(11) NOT NULL AUTO_INCREMENT,
  `idTamanoPizza` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idPizza`),
  INDEX `idTamanoPizza_idx` (`idTamanoPizza` ASC),
  CONSTRAINT `idTamanoPizza`
    FOREIGN KEY (`idTamanoPizza`)
    REFERENCES `pizzaok`.`TamanoPizza` (`idTamanoPizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pizzaok`.`PizzaPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaok`.`PizzaPedido` (
  `idPizzaPedido` INT(11) NOT NULL AUTO_INCREMENT,
  `idPizza` INT(11) NOT NULL,
  `idPedido` INT(11) NOT NULL,
  PRIMARY KEY (`idPizzaPedido`),
  INDEX `idPizza_idx` (`idPizza` ASC),
  INDEX `idPedido_idx` (`idPedido` ASC),
  CONSTRAINT `idPedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `pizzaok`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPizza`
    FOREIGN KEY (`idPizza`)
    REFERENCES `pizzaok`.`Pizza` (`idPizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
